FROM python:3.11.4-bookworm

WORKDIR /usr/src/app

ENV POETRY_VERSION=1.7.0

# prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE 1
# ensure Python output is sent directly to the terminal without buffering
ENV PYTHONUNBUFFERED 1

RUN set -xe apt-get install -y libpq-dev

RUN apt-get update
RUN apt-get install --no-install-recommends -y
RUN apt-get install locales -y
RUN sed -i '/de_DE.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE:de
ENV LC_ALL de_DE.UTF-8
RUN apt-get install --no-install-recommends -y bash
RUN apt-get install --no-install-recommends -y build-essential
RUN apt-get install --no-install-recommends -y curl
RUN apt-get install --no-install-recommends -y gettext
RUN apt-get install --no-install-recommends -y libpq-dev
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - && apt-get update -yq && apt-get install -yq nodejs

# Cleaning cache:
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
RUN pip install "poetry==$POETRY_VERSION" && poetry --

COPY ./poetry.lock .
COPY ./pyproject.toml .

RUN poetry config virtualenvs.create false && poetry install --no-root

#RUN chmod 755 ./scripts/entrypoint.sh
COPY ./entrypoint.sh .
RUN chmod +x /usr/src/app/entrypoint.sh

COPY ./dj_app ./dj_app
COPY ./config ./config
COPY ./static ./static
RUN mkdir ./logs
RUN mkdir ./staticfiles
RUN mkdir ./mediafiles

COPY ./templates ./templates
COPY ./Makefile .
COPY ./manage.py .
COPY ./tailwind.config.js .
RUN npm init -y
RUN npm install tailwindcss postcss-cli autoprefixer flowbite

ENTRYPOINT ["bash", "-e", "/usr/src/app/entrypoint.sh"]
