FROM python:3.11.4-bookworm
WORKDIR /usr/src/app
ENV POETRY_VERSION=1.7.0
# prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE 1
# ensure Python output is sent directly to the terminal without buffering
ENV PYTHONUNBUFFERED 1
RUN set -xe apt-get install -y libpq-dev
RUN apt-get update
RUN apt-get install --no-install-recommends -y
RUN apt-get install locales -y
RUN apt-get install --no-install-recommends -y bash
RUN apt-get install --no-install-recommends -y build-essential
RUN apt-get install --no-install-recommends -y curl
RUN apt-get install --no-install-recommends -y gettext
RUN apt-get install --no-install-recommends -y libpq-dev
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - && apt-get update -yq && apt-get install -yq nodejs
# Cleaning cache:
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
# Install python packages
RUN pip install "poetry==$POETRY_VERSION" && poetry --
COPY ./pyproject.toml .
RUN poetry config virtualenvs.create false && poetry install --no-root

COPY ./entrypoint.sh .
COPY ./dj_app ./dj_app
COPY ./config ./config
COPY ./static ./static
COPY ./templates ./templates
COPY ./Makefile .
COPY ./manage.py .
COPY ./tailwind.config.js .
COPY ./logs ./logs
COPY ./package.json .

RUN chmod +x /usr/src/app/entrypoint.sh
RUN npm install
# ENTRYPOINT ["bash", "-e", "/usr/src/app/entrypoint.sh"]
